apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-web-app
  namespace: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-web-app
  template:
    metadata:
      labels:
        app: weather-web-app
    spec:
      containers:
        - name: weather-web-app
          image: muhammadibrahim7860/weather-web-app:latest
          ports:
            - containerPort: 3000

