apiVersion: v1
kind: Service
metadata:
  name: weather-web-app
  namespace: weather
spec:
  type: NodePort
  selector:
    app: weather-web-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30010


